azs:
- name: z1
  cloud_properties:
    availability_zone: ((az))
- name: z2
  cloud_properties:
    availability_zone: ((az))
- name: z3
  cloud_properties:
    availability_zone: ((az))

vm_types:
- name: default
  cloud_properties:
    instance_type: ecs.m4.small
    ephemeral_disk: {size: 20_480}
- name: large
  cloud_properties:
    instance_type: ecs.m4.large
    ephemeral_disk: {size: 51_200}

disk_types:
- name: default
  disk_size: 10_240
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    reserved: [((internal_gw))/30]
    cloud_properties:
      vsiwtch_id: ((vswitch_id))
      security_group_id: ((security_group_id))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
